# **2.7 Transposes and Permutations**

- The columns of $A^T$ are the rows of $A$.  
- If $A$ is $m \times n$, then $A^T$ is $n \times m$.

Example:  
If  
$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 0 & 4 \end{bmatrix}
$$
then  
$$
A^T = \begin{bmatrix} 1 & 0 \\ 2 & 0 \\ 3 & 4 \end{bmatrix}
$$

- The entry in row $i$, column $j$ of $A^T$ comes from row $j$, column $i$ of $A$:  
$$
(A^T)_{ij} = A_{ji}
$$

- The transpose of a **lower triangular** matrix is **upper triangular** (but the inverse remains lower).  


### **Transpose Rules**
- **Sum:**  
  $$
  (A + B)^T = A^T + B^T
  $$
- **Product:**  
  $$
  (AB)^T = B^T A^T
  $$
- **Inverse:**  
  $$
  (A^{-1})^T = (A^T)^{-1}
  $$

- $Ax$ combines columns of $A$, while $x^T A^T$ combines rows of $A^T$.  
- If $A = LDU$, then  
  $$
  A^T = U^T D^T L^T
  $$
  The pivot matrix satisfies $D = D^T$.

- From $A^{-1}A = I$, transpose gives:  
  $$
  A^T (A^{-1})^T = I
  $$
  So $A^T$ is invertible when $A$ is.

In [1]:
def transpose(A):
    rows = len(A)
    cols = len(A[0])
    return [[A[i][j] for i in range(rows)] for j in range(cols)]

A = [
    [1, 2, 3],
    [0, 0, 4]
]

transpose(A)

[[1, 0], [2, 0], [3, 4]]

### **The Meaning of Inner Products**

- **Inner (dot) product:** $x^T y$ — a scalar.  
- **Outer product:** $xy^T$ — a matrix.  

- Inner product identity:  
  $$
  (Ax)^T y = x^T (A^T y)
  $$

### **Symmetric Matrices**

- Definition: $S$ is symmetric if $S^T = S$ (so $s_{ji} = s_{ij}$).  
- The inverse of a symmetric matrix is also symmetric.  
- A symmetric matrix can be built as $A A^T$.


### **Symmetric Products $A^T A$ and $A A^T$ and $LDL^T$**

- The transpose of $A^T A$ is itself:  
  $$
  (A^T A)^T = A^T A
  $$
- Generally, $A^T A \neq A A^T$.

- If $S$ is symmetric and factored with no row exchanges,
  $$
  S = L D U \quad \text{with} \quad U = L^T
  $$
  giving the symmetric factorization:
  $$
  S = L D L^T
  $$


In [5]:
import numpy as np

def symmetrize(A, mode="AAT"):
    A = np.array(A, dtype=float)

    if mode == "AAT":
        return A @ A.T
    elif mode == "ATA":
        return A.T @ A
    else:
        raise ValueError("mode must be 'AAT' or 'ATA'")

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

S = symmetrize(A, mode="AAT")
print(S)

[[ 5. 11. 17.]
 [11. 25. 39.]
 [17. 39. 61.]]


### **Permutation Matrices**

- Definition: A permutation matrix $P$ has the rows of the identity matrix in any order.  
- There are $n!$ permutation matrices of order $n$.  
- Important facts:  
  $$
  P^{-1} = P^T, \qquad P P^T = I
  $$

- Row exchanges before elimination lead to:
  $$
  PA = LU
  $$

In [15]:
import numpy as np
import itertools
import math

def generate_permutation_matrices(n):
    perms = list(itertools.permutations(range(n)))
    matrices = []

    for p in perms:
        M = np.zeros((n, n), dtype=int)
        for row, col in enumerate(p):
            M[row, col] = 1
        matrices.append(M)
        print(M, "\n")

    print(f"Total  permutation matrices: {math.factorial(n)}")
    
print(f"Permutation Matrices: ")
generate_permutation_matrices(3)

Permutation Matrices: 
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1 0 0]
 [0 0 1]
 [0 1 0]] 

[[0 1 0]
 [1 0 0]
 [0 0 1]] 

[[0 1 0]
 [0 0 1]
 [1 0 0]] 

[[0 0 1]
 [1 0 0]
 [0 1 0]] 

[[0 0 1]
 [0 1 0]
 [1 0 0]] 

Total  permutation matrices: 6



### **The $PA = LU$ Factorization with Row Exchanges**

Main question: *Where to collect the $P_{ij}$ matrices?*

1. **Row exchanges first:**  
   Compute the permutation matrix $P$ that puts the rows of $A$ in a good pivot order. Then factor:  
   $$
   PA = LU
   $$

2. **Row exchanges after elimination:**  
   Pivot rows end in the wrong order; a permutation $P_1$ restores triangular order:  
   $$
   A = L^1 P^1 U^1
   $$

- If $A$ is invertible, some permutation $P$ will reorder its rows so that $PA$ has a full set of pivots and can be factored.


**Key Ideas**

1. The transpose puts the rows of $A$ into the columns of $A^T$, so $(A^T)_{ij} = A_{ji}$.  
2. $(AB)^T = B^T A^T$, and $(A^{-1})^T = (A^T)^{-1}$.  
3. The dot product is $x^T y$; and $(Ax)^T y = x^T (A^T y)$.  
4. If $S$ is symmetric, its factorization is symmetric:  
   $$
   S = L D L^T
   $$
5. A permutation matrix has one 1 per row and column, and satisfies $P^T = P^{-1}$.  
6. There are $n!$ permutation matrices (half even, half odd).  
7. If $A$ is invertible, a permutation $P$ will reorder its rows for a valid $PA = LU$ factorization.
